export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILED = 'FETCH_WEATHER_FAILED';

export const SET_AVARAGE_WEATHER_DATA = 'SET_AVARAGE_WEATHER_DATA';

export const SET_DETAILED_WEATHER_DATA = 'SET_DETAILED_WEATHER_DATA';
