export const FETCH_FIVEDAYFORECAST_START = 'FETCH_FIVEDAYFORECAST_START';
export const FETCH_FIVEDAYFORECAST_SUCCESS = 'FETCH_FIVEDAYFORECAST_SUCCESS';
export const FETCH_FIVEDAYFORECAST_FAILED = 'FETCH_FIVEDAYFORECAST_FAILED';

export const SET_AVARAGE_WEATHER_DATA = 'SET_AVARAGE_WEATHER_DATA';

export const SET_DETAILED_WEATHER_DATA = 'SET_DETAILED_WEATHER_DATA';

export const RESET_ERRORS = 'RESET_ERRORS';

export const FETCH_TODAYDAYFORECAST_START = 'FETCH_TODAYDAYFORECAST_START';
export const FETCH_TODAYDAYFORECAST_SUCCESS = 'FETCH_TODAYDAYFORECAST_SUCCESS';
export const FETCH_TODAYDAYFORECAST_FAILED = 'FETCH_TODAYDAYFORECAST_FAILED';
